cwlVersion: v1.0
class: Workflow


inputs:

  
  fastq_file_1:
    type: File
    format: "http://edamontology.org/format_1930"
    label: "FASTQ input file 1"
    doc: "Unmapped reads in a FASTQ format"

  fastq_file_2:
    type: File
    format: "http://edamontology.org/format_1930"
    label: "FASTQ input file 2"
    doc: "Unmapped reads in a FASTQ format"


outputs:

  fastq_1_qc_report:
    type: File
    format: "http://edamontology.org/format_2331"
    outputSource: qc_fastq_1/html_file
    label: "QC report for FASTQ file 1"
    doc: "Html report generated by FastQC"

  fastq_1_qc_report:
    type: File
    format: "http://edamontology.org/format_2331"
    outputSource: qc_fastq_2/html_file
    label: "QC report for FASTQ file 2"
    doc: "Html report generated by FastQC"


steps:


  qc_fastq_1:
    run: ../include/tools/fastqc.cwl
    in:
      reads_file: fastq_file_1
    out: [html_file]

  qc_fastq_2:
    run: ../include/tools/fastqc.cwl
    in:
      reads_file: fastq_file_2
    out: [html_file]


$namespaces:
  s: http://schema.org/

$schemas:
- http://schema.org/docs/schema_org_rdfa.html

s:name: "quality_control"
s:downloadUrl: https://github.com/michael-kotliar/cwl-workflows/blob/master/workflows/quality_control.cwl
s:codeRepository: ttps://github.com/michael-kotliar/cwl-workflows
s:license: http://www.apache.org/licenses/LICENSE-2.0

s:isPartOf:
  class: s:CreativeWork
  s:name: Common Workflow Language
  s:url: http://commonwl.org/

s:creator:
- class: s:Organization
  s:legalName: "Cincinnati Children's Hospital Medical Center"
  s:location:
  - class: s:PostalAddress
    s:addressCountry: "USA"
    s:addressLocality: "Cincinnati"
    s:addressRegion: "OH"
    s:postalCode: "45229"
    s:streetAddress: "3333 Burnet Ave"
    s:telephone: "+1(513)636-4200"
  s:logo: "https://www.cincinnatichildrens.org/-/media/cincinnati%20childrens/global%20shared/childrens-logo-new.png"
  s:department:
  - class: s:Organization
    s:legalName: "Allergy and Immunology"
    s:department:
    - class: s:Organization
      s:legalName: "Barski Research Lab"
      s:member:
      - class: s:Person
        s:name: Michael Kotliar
        s:email: mailto:michael.kotliar@cchmc.org
        s:sameAs:
        - id: http://orcid.org/0000-0002-6486-3898

doc: |
  Runs quality control tool both input FASTQ files

s:about: |
  Runs quality control tool both input FASTQ files